### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by michelefa1988** [regulaforensics/helm-charts#17]
Hi,

Does your helm chart support prometheus/grafana metrics. We would like to keep tabs on the number of scans/. times/ successes. failures etc. 

I do not find a way to do it on your docreader/ facesdk helm chart.

**Comment by AndreiPaulau** [comment]
Hi @michelefa1988,

Our apps do support Prometheus via `/metrics` endpoint
https://docs.regulaforensics.com/develop/face-sdk/web-service/administration/monitoring/

**Comment by AndreiPaulau** [comment]
https://github.com/regulaforensics/helm-charts/releases/tag/faceapi-0.1.4
