### ISSUE TITLE
hpa template issues when setting targetMemoryUtilizationPercentage

### ISSUE THREAD

**Issue by fernandonogueira-au** [regulaforensics/helm-charts#26]
hpa template for docreader and faceapi are getting the kubernetes version for memory using the wrong function causing the template to fail when trying to set the targetMemoryUtilizationPercentage.  

https://github.com/regulaforensics/helm-charts/blob/docreader-0.5.1/charts/docreader/templates/hpa.yaml#L36
https://github.com/regulaforensics/helm-charts/blob/faceapi-0.2.3/charts/faceapi/templates/hpa.yaml#L36

>>>>>

helm upgrade regula regulaforensics/docreader --namespace=regula -f values.yaml

Error: UPGRADE FAILED: template: docreader/templates/hpa.yaml:36:40: executing "docreader/templates/hpa.yaml" at <include "common.capabilities.kubeVersion" .>: error calling include: template: no template "common.capabilities.kubeVersion" associated with template "gotpl"

**Comment by AndreiPaulau** [comment]
Hello,

Thanks for pointing to that.
Will be fixed in the nearest Major release.
Will be sticking to the minimum required Kuberenetes version 1.23-0 and respective API versions

**Comment by AndreiPaulau** [comment]
Hi,
Please check [docreader 1.0.0 release](https://github.com/regulaforensics/helm-charts/releases/tag/docreader-1.0.0)

**Comment by fernandonogueira-au** [comment]
@AndreiPaulau just a FYI the same is happening for the faceapi .

**Comment by AndreiPaulau** [comment]
Hi, yep, will be fixed within major faceapi helm chart release as well.
Closing for now
