### ISSUE TITLE
Regula Docreader 7.0

### ISSUE THREAD

**Issue by michelefa1988** [regulaforensics/helm-charts#27]
Hi, 

Do you need to upgrade the regula helm chart before we update to regula 7.x. We have upgraded to docreader 7.x using the current helm chart and we get an error license not found. 

Please advise

**Comment by AndreiPaulau** [comment]
Hello,

Yes, we gonna publish the new chart soon.
Mind, this is a major update for the chart as well (requires transition to config.yaml configuration file), thus not compatible with the previous 0.5.1 chart version, so should be tested before the upgrade
