### ISSUE TITLE
charts/docreader/templates/session-api-transactions-pvc.yaml error

### ISSUE THREAD

**Issue by hunter-luo666** [regulaforensics/helm-charts#30]
{{- if .Values.config.service.sessionApi.transactions.storageClassName }}
  {{- if (eq "-" .Values.config.service.sessionApi.transactions.storageClassName) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.config.service.sessionApi.transactions.storageClassName }}"
  
  
  should update to：
    {{- if .Values.config.service.sessionApi.transactions.**persistence**.storageClassName }}
  {{- if (eq "-" .Values.config.service.sessionApi.transactions.**persistence**.storageClassName) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.config.service.sessionApi.transactions.**persistence**.storageClassName }}"

**Comment by AndreiPaulau** [comment]
Hello @hunter-luo666,

Thank you for noticing that, we'll fix it shortly!

**Comment by AndreiPaulau** [comment]
Fixed with https://github.com/regulaforensics/helm-charts/pull/31
